// http://github.com/dvkndn/typed-tailwind
export const Style = (): SStyle => new SStyle();

class SStyle {
  value = "";

  // Getter methods
  // Why "$":
  // - https://github.com/microsoft/TypeScript/issues/2361
  // - https://github.com/microsoft/TypeScript/issues/4538
  // - https://en.wikipedia.org/wiki/Regular_expression
  $(): string { return this.value; }
  [Symbol.toPrimitive](): string { return this.$(); }

  // Building methods
  private add(value: string): SStyle {
    this.value = `${this.value} ${value}`;
    return this;
  }

  // Styling methods
  block(): SStyle { return this.add("block"); }
  inlineBlock(): SStyle { return this.add("inline-block"); }
  inline(): SStyle { return this.add("inline"); }
  flex(): SStyle { return this.add("flex"); }
  inlineFlex(): SStyle { return this.add("inline-flex"); }
  table(): SStyle { return this.add("table"); }
  tableRow(): SStyle { return this.add("table-row"); }
  tableCell(): SStyle { return this.add("table-cell"); }
  hidden(): SStyle { return this.add("hidden"); }
  flex1(): SStyle { return this.add("flex-1"); }
  flexNone(): SStyle { return this.add("flex-none"); }
  h4(): SStyle { return this.add("h-4"); }
  h8(): SStyle { return this.add("h-8"); }
  h12(): SStyle { return this.add("h-12"); }
  h16(): SStyle { return this.add("h-16"); }
  h24(): SStyle { return this.add("h-24"); }
  h32(): SStyle { return this.add("h-32"); }
  h40(): SStyle { return this.add("h-40"); }
  h48(): SStyle { return this.add("h-48"); }
  h60(): SStyle { return this.add("h-60"); }
  hFull(): SStyle { return this.add("h-full"); }
  hScreen(): SStyle { return this.add("h-screen"); }
  overflowAuto(): SStyle { return this.add("overflow-auto"); }
  overflowHidden(): SStyle { return this.add("overflow-hidden"); }
  overflowVisible(): SStyle { return this.add("overflow-visible"); }
  overflowScroll(): SStyle { return this.add("overflow-scroll"); }
  overflowXAuto(): SStyle { return this.add("overflow-x-auto"); }
  overflowYAuto(): SStyle { return this.add("overflow-y-auto"); }
  overflowXHidden(): SStyle { return this.add("overflow-x-hidden"); }
  overflowYHidden(): SStyle { return this.add("overflow-y-hidden"); }
  overflowXVisible(): SStyle { return this.add("overflow-x-visible"); }
  overflowYVisible(): SStyle { return this.add("overflow-y-visible"); }
  overflowXScroll(): SStyle { return this.add("overflow-x-scroll"); }
  overflowYScroll(): SStyle { return this.add("overflow-y-scroll"); }
  scrollingTouch(): SStyle { return this.add("scrolling-touch"); }
  scrollingAuto(): SStyle { return this.add("scrolling-auto"); }
  text0(): SStyle { return this.add("text-0"); }
  text1(): SStyle { return this.add("text-1"); }
  text2(): SStyle { return this.add("text-2"); }
  text3(): SStyle { return this.add("text-3"); }
  text4(): SStyle { return this.add("text-4"); }
  text5(): SStyle { return this.add("text-5"); }
  text6(): SStyle { return this.add("text-6"); }
  text7(): SStyle { return this.add("text-7"); }
  text8(): SStyle { return this.add("text-8"); }
  text9(): SStyle { return this.add("text-9"); }
  textCurrentColor(): SStyle { return this.add("text-currentColor"); }
  textTransparent(): SStyle { return this.add("text-transparent"); }
  textA(): SStyle { return this.add("text-A"); }
  textB(): SStyle { return this.add("text-B"); }
  textC(): SStyle { return this.add("text-C"); }
  textD(): SStyle { return this.add("text-D"); }
  textE(): SStyle { return this.add("text-E"); }
  textF(): SStyle { return this.add("text-F"); }
  text0At90(): SStyle { return this.add("text-0at90"); }
  selectNone(): SStyle { return this.add("select-none"); }
  selectText(): SStyle { return this.add("select-text"); }
  selectAll(): SStyle { return this.add("select-all"); }
  selectAuto(): SStyle { return this.add("select-auto"); }
  w4(): SStyle { return this.add("w-4"); }
  w8(): SStyle { return this.add("w-8"); }
  w12(): SStyle { return this.add("w-12"); }
  w16(): SStyle { return this.add("w-16"); }
  w24(): SStyle { return this.add("w-24"); }
  w32(): SStyle { return this.add("w-32"); }
  w40(): SStyle { return this.add("w-40"); }
  w48(): SStyle { return this.add("w-48"); }
  w60(): SStyle { return this.add("w-60"); }
  wFull(): SStyle { return this.add("w-full"); }
  wScreen(): SStyle { return this.add("w-screen"); }
  bg0(): SStyle { return this.add("bg-0"); }
  bg1(): SStyle { return this.add("bg-1"); }
  bg2(): SStyle { return this.add("bg-2"); }
  bg3(): SStyle { return this.add("bg-3"); }
  bg4(): SStyle { return this.add("bg-4"); }
  bg5(): SStyle { return this.add("bg-5"); }
  bg6(): SStyle { return this.add("bg-6"); }
  bg7(): SStyle { return this.add("bg-7"); }
  bg8(): SStyle { return this.add("bg-8"); }
  bg9(): SStyle { return this.add("bg-9"); }
  bgCurrentColor(): SStyle { return this.add("bg-currentColor"); }
  bgTransparent(): SStyle { return this.add("bg-transparent"); }
  bgA(): SStyle { return this.add("bg-A"); }
  bgB(): SStyle { return this.add("bg-B"); }
  bgC(): SStyle { return this.add("bg-C"); }
  bgD(): SStyle { return this.add("bg-D"); }
  bgE(): SStyle { return this.add("bg-E"); }
  bgF(): SStyle { return this.add("bg-F"); }
  bg0At90(): SStyle { return this.add("bg-0at90"); }
  fontMono(): SStyle { return this.add("font-mono"); }
  p4(): SStyle { return this.add("p-4"); }
  p8(): SStyle { return this.add("p-8"); }
  p12(): SStyle { return this.add("p-12"); }
  p16(): SStyle { return this.add("p-16"); }
  p24(): SStyle { return this.add("p-24"); }
  p32(): SStyle { return this.add("p-32"); }
  p40(): SStyle { return this.add("p-40"); }
  p48(): SStyle { return this.add("p-48"); }
  p60(): SStyle { return this.add("p-60"); }
  py4(): SStyle { return this.add("py-4"); }
  px4(): SStyle { return this.add("px-4"); }
  py8(): SStyle { return this.add("py-8"); }
  px8(): SStyle { return this.add("px-8"); }
  py12(): SStyle { return this.add("py-12"); }
  px12(): SStyle { return this.add("px-12"); }
  py16(): SStyle { return this.add("py-16"); }
  px16(): SStyle { return this.add("px-16"); }
  py24(): SStyle { return this.add("py-24"); }
  px24(): SStyle { return this.add("px-24"); }
  py32(): SStyle { return this.add("py-32"); }
  px32(): SStyle { return this.add("px-32"); }
  py40(): SStyle { return this.add("py-40"); }
  px40(): SStyle { return this.add("px-40"); }
  py48(): SStyle { return this.add("py-48"); }
  px48(): SStyle { return this.add("px-48"); }
  py60(): SStyle { return this.add("py-60"); }
  px60(): SStyle { return this.add("px-60"); }
  pt4(): SStyle { return this.add("pt-4"); }
  pr4(): SStyle { return this.add("pr-4"); }
  pb4(): SStyle { return this.add("pb-4"); }
  pl4(): SStyle { return this.add("pl-4"); }
  pt8(): SStyle { return this.add("pt-8"); }
  pr8(): SStyle { return this.add("pr-8"); }
  pb8(): SStyle { return this.add("pb-8"); }
  pl8(): SStyle { return this.add("pl-8"); }
  pt12(): SStyle { return this.add("pt-12"); }
  pr12(): SStyle { return this.add("pr-12"); }
  pb12(): SStyle { return this.add("pb-12"); }
  pl12(): SStyle { return this.add("pl-12"); }
  pt16(): SStyle { return this.add("pt-16"); }
  pr16(): SStyle { return this.add("pr-16"); }
  pb16(): SStyle { return this.add("pb-16"); }
  pl16(): SStyle { return this.add("pl-16"); }
  pt24(): SStyle { return this.add("pt-24"); }
  pr24(): SStyle { return this.add("pr-24"); }
  pb24(): SStyle { return this.add("pb-24"); }
  pl24(): SStyle { return this.add("pl-24"); }
  pt32(): SStyle { return this.add("pt-32"); }
  pr32(): SStyle { return this.add("pr-32"); }
  pb32(): SStyle { return this.add("pb-32"); }
  pl32(): SStyle { return this.add("pl-32"); }
  pt40(): SStyle { return this.add("pt-40"); }
  pr40(): SStyle { return this.add("pr-40"); }
  pb40(): SStyle { return this.add("pb-40"); }
  pl40(): SStyle { return this.add("pl-40"); }
  pt48(): SStyle { return this.add("pt-48"); }
  pr48(): SStyle { return this.add("pr-48"); }
  pb48(): SStyle { return this.add("pb-48"); }
  pl48(): SStyle { return this.add("pl-48"); }
  pt60(): SStyle { return this.add("pt-60"); }
  pr60(): SStyle { return this.add("pr-60"); }
  pb60(): SStyle { return this.add("pb-60"); }
  pl60(): SStyle { return this.add("pl-60"); }
  rounded4(): SStyle { return this.add("rounded-4"); }
  roundedFull(): SStyle { return this.add("rounded-full"); }
  roundedT4(): SStyle { return this.add("rounded-t-4"); }
  roundedR4(): SStyle { return this.add("rounded-r-4"); }
  roundedB4(): SStyle { return this.add("rounded-b-4"); }
  roundedL4(): SStyle { return this.add("rounded-l-4"); }
  roundedTFull(): SStyle { return this.add("rounded-t-full"); }
  roundedRFull(): SStyle { return this.add("rounded-r-full"); }
  roundedBFull(): SStyle { return this.add("rounded-b-full"); }
  roundedLFull(): SStyle { return this.add("rounded-l-full"); }
  roundedTl4(): SStyle { return this.add("rounded-tl-4"); }
  roundedTr4(): SStyle { return this.add("rounded-tr-4"); }
  roundedBr4(): SStyle { return this.add("rounded-br-4"); }
  roundedBl4(): SStyle { return this.add("rounded-bl-4"); }
  roundedTlFull(): SStyle { return this.add("rounded-tl-full"); }
  roundedTrFull(): SStyle { return this.add("rounded-tr-full"); }
  roundedBrFull(): SStyle { return this.add("rounded-br-full"); }
  roundedBlFull(): SStyle { return this.add("rounded-bl-full"); }
  bgAuto(): SStyle { return this.add("bg-auto"); }
  bgCover(): SStyle { return this.add("bg-cover"); }
  bgContain(): SStyle { return this.add("bg-contain"); }
  flexRow(): SStyle { return this.add("flex-row"); }
  flexRowReverse(): SStyle { return this.add("flex-row-reverse"); }
  flexCol(): SStyle { return this.add("flex-col"); }
  flexColReverse(): SStyle { return this.add("flex-col-reverse"); }
  static(): SStyle { return this.add("static"); }
  fixed(): SStyle { return this.add("fixed"); }
  absolute(): SStyle { return this.add("absolute"); }
  relative(): SStyle { return this.add("relative"); }
  sticky(): SStyle { return this.add("sticky"); }
  inset0(): SStyle { return this.add("inset-0"); }
  insetY0(): SStyle { return this.add("inset-y-0"); }
  insetX0(): SStyle { return this.add("inset-x-0"); }
  top0(): SStyle { return this.add("top-0"); }
  right0(): SStyle { return this.add("right-0"); }
  bottom0(): SStyle { return this.add("bottom-0"); }
  left0(): SStyle { return this.add("left-0"); }
  mAuto(): SStyle { return this.add("m-auto"); }
  myAuto(): SStyle { return this.add("my-auto"); }
  mxAuto(): SStyle { return this.add("mx-auto"); }
  mtAuto(): SStyle { return this.add("mt-auto"); }
  mrAuto(): SStyle { return this.add("mr-auto"); }
  mbAuto(): SStyle { return this.add("mb-auto"); }
  mlAuto(): SStyle { return this.add("ml-auto"); }
  leading1(): SStyle { return this.add("leading-1"); }
  leading16(): SStyle { return this.add("leading-16"); }
  textLeft(): SStyle { return this.add("text-left"); }
  textCenter(): SStyle { return this.add("text-center"); }
  textRight(): SStyle { return this.add("text-right"); }
  textJustify(): SStyle { return this.add("text-justify"); }
  itemsStart(): SStyle { return this.add("items-start"); }
  itemsEnd(): SStyle { return this.add("items-end"); }
  itemsCenter(): SStyle { return this.add("items-center"); }
  itemsBaseline(): SStyle { return this.add("items-baseline"); }
  itemsStretch(): SStyle { return this.add("items-stretch"); }
  justifyStart(): SStyle { return this.add("justify-start"); }
  justifyEnd(): SStyle { return this.add("justify-end"); }
  justifyCenter(): SStyle { return this.add("justify-center"); }
  justifyBetween(): SStyle { return this.add("justify-between"); }
  justifyAround(): SStyle { return this.add("justify-around"); }
  shadowPanel(): SStyle { return this.add("shadow-panel"); }
  bgFixed(): SStyle { return this.add("bg-fixed"); }
  bgLocal(): SStyle { return this.add("bg-local"); }
  bgScroll(): SStyle { return this.add("bg-scroll"); }
  bgBottom(): SStyle { return this.add("bg-bottom"); }
  bgCenter(): SStyle { return this.add("bg-center"); }
  bgLeft(): SStyle { return this.add("bg-left"); }
  bgLeftBottom(): SStyle { return this.add("bg-left-bottom"); }
  bgLeftTop(): SStyle { return this.add("bg-left-top"); }
  bgRight(): SStyle { return this.add("bg-right"); }
  bgRightBottom(): SStyle { return this.add("bg-right-bottom"); }
  bgRightTop(): SStyle { return this.add("bg-right-top"); }
  bgTop(): SStyle { return this.add("bg-top"); }
  font400(): SStyle { return this.add("font-400"); }
  font500(): SStyle { return this.add("font-500"); }
  font600(): SStyle { return this.add("font-600"); }
  font700(): SStyle { return this.add("font-700"); }
  font900(): SStyle { return this.add("font-900"); }
  text14(): SStyle { return this.add("text-14"); }
  text32(): SStyle { return this.add("text-32"); }
  text96(): SStyle { return this.add("text-96"); }
}
